# Generated by Django 4.0.4 on 2022-05-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30, verbose_name='Name of the service')),
                ('service_price', models.FloatField(default=0, verbose_name='Price of the service')),
                ('service_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of the service')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Feedback')),
                ('star_rating', models.IntegerField(default=5, verbose_name='Rating of the service')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
        ),
    ]
