# Generated by Django 4.0.4 on 2022-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=256, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
