# Generated by Django 4.0.4 on 2022-05-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
