# Generated by Django 3.2.13 on 2022-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_rating',
            field=models.FloatField(default=0, verbose_name='Average star rating for company'),
        ),
    ]
