# Generated by Django 3.2.13 on 2022-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.PositiveIntegerField(default=0.0, verbose_name='price of one service'),
        ),
    ]
