# Generated by Django 3.2.13 on 2022-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_company_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Do you want to use filters?'),
        ),
        migrations.AddField(
            model_name='request',
            name='max_cost',
            field=models.FloatField(default=100, verbose_name='Cost for filters'),
        ),
        migrations.AddField(
            model_name='request',
            name='min_rating',
            field=models.FloatField(default=3, verbose_name='Rating for filters'),
        ),
    ]
