# Generated by Django 3.2.13 on 2022-06-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Star rating of the service'),
        ),
    ]
