# Generated by Django 3.2.13 on 2022-06-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220607_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='search_category',
            field=models.CharField(default='Vacuuming', max_length=50, verbose_name='Category for filters'),
        ),
    ]
