# Generated by Django 3.2.13 on 2022-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_rating',
            field=models.FloatField(null=True, verbose_name='Average star rating for company'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category of the service'),
        ),
        migrations.AlterField(
            model_name='request',
            name='area',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Area of cleaning'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of the service'),
        ),
    ]
