# Generated by Django 4.0.4 on 2022-05-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):



    dependencies = [('core', '0003_service_migration')
    ]

    operations = [

        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pend', 'Pending'), ('Canc', 'Canceled'), ('Comp', 'Completed')], default='Pend', max_length=4)),
            ],
        ),

    ]
