# Generated by Django 3.2.13 on 2022-06-08 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_request_search_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 15, 54, 4, 420562, tzinfo=utc), verbose_name='Time of the service'),
        ),
    ]
