# Generated by Django 3.2.13 on 2022-06-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220603_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratings_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of reviews'),
        ),
    ]
