# Generated by Django 3.2.13 on 2022-06-08 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 16, 1, 11, 831540, tzinfo=utc), verbose_name='Time of the service'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 16, 1, 11, 834532, tzinfo=utc), verbose_name='Time of the comment'),
        ),
    ]
