# Generated by Django 3.2.13 on 2022-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_ratings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject of the email')),
                ('message', models.TextField(verbose_name='Message of the email')),
                ('sender', models.CharField(max_length=50, verbose_name='Name of the sender')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Name of the receiver')),
            ],
        ),
    ]
