# Generated by Django 3.2.13 on 2022-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='minutes',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='period of cleaning'),
        ),
    ]
