# Generated by Django 3.2.13 on 2022-06-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='company',
        ),
        migrations.RemoveField(
            model_name='response',
            name='status',
        ),
        migrations.AddField(
            model_name='response',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=True, verbose_name='Accepted or cancelled'),
        ),
    ]
