# Generated by Django 3.2.13 on 2022-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220604_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Canceled'), ('Completed', 'Completed'), ('Accepted', 'Accepted'), ('In process', 'In process')], default='Pending', max_length=10),
        ),
    ]
