# Generated by Django 3.2.13 on 2022-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_requeststatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='service',
            new_name='final_service',
        ),
        migrations.AddField(
            model_name='request',
            name='service_list',
            field=models.ManyToManyField(related_name='service_list', to='core.Service'),
        ),
    ]
