# Generated by Django 4.0.2 on 2022-05-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_custom_sql_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category of the service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
