# Generated by Django 3.2.13 on 2022-06-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220605_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='final_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
