# Generated by Django 3.2.13 on 2022-06-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_request_final_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
