# Generated by Django 3.2.13 on 2022-06-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_response_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
            preserve_default=False,
        ),
    ]
