# Generated by Django 3.2.13 on 2022-06-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_response_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='company',
        ),
    ]
