# Generated by Django 4.0.4 on 2022-05-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Full address')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of the service')),
                ('area', models.FloatField(default=0, verbose_name='Area of cleaning')),
                ('cost_total', models.FloatField(verbose_name='Total cost of the service')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Pending, Canceled, Completed')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full name of the user')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of the user')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.role')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the service')),
                ('cost', models.FloatField(default=0.0, verbose_name='price of one service')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, verbose_name='Star rating of the service')),
                ('feedback', models.TextField(blank=True, verbose_name='Comment of the service')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of the comment')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.request')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.service'),
        ),
        migrations.AddField(
            model_name='request',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.requeststatus'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.user'),
        ),
    ]
