# Generated by Django 4.0.4 on 2022-05-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_request_requeststatus_user_service_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='aoaoao',
            field=models.TextField(null=True),
        ),
    ]
