# Generated by Django 4.0.4 on 2022-05-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_request_aoaoao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='aoaoao',
        ),
    ]
