# Generated by Django 4.0.4 on 2022-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_request_aoaoao'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='a',
            field=models.TextField(null=True),
        ),
    ]
