# Generated by Django 4.0.4 on 2022-05-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_request_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='a',
        ),
    ]
